name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            6.0.x
            7.0.x
    
      - name: Restore
        run: dotnet restore IT.Mapping.sln
    
      - name: Build
        run: dotnet build IT.Mapping.sln --configuration Release --no-restore 
        
      - name: Test
        run: dotnet test IT.Mapping.Tests/IT.Mapping.Tests.csproj --no-restore

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish IT.Mapping.Mapster
        uses: pairbit/publish-nuget@v2.6.0
        with:
            PROJECT_FILE_PATH: IT.Mapping.Mapster/IT.Mapping.Mapster.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            
      - name: Publish IT.Mapping.AutoMapper
        uses: pairbit/publish-nuget@v2.6.0
        with:
            PROJECT_FILE_PATH: IT.Mapping.AutoMapper/IT.Mapping.AutoMapper.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            
      - name: Publish IT.Mapping
        uses: pairbit/publish-nuget@v2.6.0
        with:
            PROJECT_FILE_PATH: IT.Mapping/IT.Mapping.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: true
